# Configuration parameters for data recording node.

output_directory: '/'

topics:
   - '/*'
#  - '/example/(.*)'
#  - '/camera/depth/image_raw'
#  - '/camera/depth/camera_info'
#  - '/camera/rgb/image_raw'
#  - '/camera/rgb/camera_info'
